x1=int(input("digitar valor x1  "))
y1=int(input("digitar valor y1  "))
x2=int(input("digitar valor x2  "))
y2=int(input("digitar valor y2  "))
d=((x2-x1)**2+(y2-y1)**2)**(1/2)
print("el resultado de d es:",d )
print(d)